export const LocalTextsEn = {
  t_app_shop: 'Shop',
  t_app_list_empty: 'List empty',
  t_app_profile: 'Profile',
  t_app_cart: 'Cart',
  t_app_bestshop: 'Best Shop',
  t_app_account: 'Account',
  t_app_totalprice: 'Total: $',
  t_app_addToCart: 'Add to cart',
  t_app_addedToCart: 'Added',
  t_app_login: 'Login',
  t_app_email: 'Email',
  t_app_pass: 'Password',
  t_app_logout: 'LogOut',
  t_app_username: 'Username',
  t_app_confirm: 'Do you want to log out?',
  t_app_cancel: 'Cancel',
  t_app_yes: 'Yes',
  t_app_enteremail: 'Enter email',
};
